# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(645, 632)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        Dialog.setFont(font)
        Dialog.setAutoFillBackground(True)
        Dialog.setStyleSheet("")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.chooseScheme = QtWidgets.QComboBox(self.tab)
        self.chooseScheme.setObjectName("chooseScheme")
        self.chooseScheme.addItem("")
        self.chooseScheme.addItem("")
        self.verticalLayout_5.addWidget(self.chooseScheme)
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.showSchemeFirst = QtWidgets.QLabel(self.tab)
        self.showSchemeFirst.setMinimumSize(QtCore.QSize(0, 210))
        self.showSchemeFirst.setText("")
        self.showSchemeFirst.setAlignment(QtCore.Qt.AlignCenter)
        self.showSchemeFirst.setObjectName("showSchemeFirst")
        self.verticalLayout.addWidget(self.showSchemeFirst)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setMinimumSize(QtCore.QSize(0, 20))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.showFormulaFirst = QtWidgets.QLabel(self.tab)
        self.showFormulaFirst.setText("")
        self.showFormulaFirst.setAlignment(QtCore.Qt.AlignCenter)
        self.showFormulaFirst.setObjectName("showFormulaFirst")
        self.verticalLayout_5.addWidget(self.showFormulaFirst)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.q1Label = QtWidgets.QLabel(self.tab)
        self.q1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.q1Label.setObjectName("q1Label")
        self.verticalLayout_10.addWidget(self.q1Label)
        self.q1Value = QtWidgets.QDoubleSpinBox(self.tab)
        self.q1Value.setMaximum(1.0)
        self.q1Value.setSingleStep(0.1)
        self.q1Value.setObjectName("q1Value")
        self.verticalLayout_10.addWidget(self.q1Value)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8)
        self.q2Value = QtWidgets.QDoubleSpinBox(self.tab)
        self.q2Value.setMaximum(1.0)
        self.q2Value.setSingleStep(0.1)
        self.q2Value.setObjectName("q2Value")
        self.verticalLayout_10.addWidget(self.q2Value)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_10.addWidget(self.label_9)
        self.q3Value = QtWidgets.QDoubleSpinBox(self.tab)
        self.q3Value.setMaximum(1.0)
        self.q3Value.setSingleStep(0.1)
        self.q3Value.setObjectName("q3Value")
        self.verticalLayout_10.addWidget(self.q3Value)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_11.addWidget(self.label_10)
        self.q4Value = QtWidgets.QDoubleSpinBox(self.tab)
        self.q4Value.setMaximum(1.0)
        self.q4Value.setSingleStep(0.1)
        self.q4Value.setObjectName("q4Value")
        self.verticalLayout_11.addWidget(self.q4Value)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_11.addWidget(self.label_11)
        self.q5Value = QtWidgets.QDoubleSpinBox(self.tab)
        self.q5Value.setMaximum(1.0)
        self.q5Value.setSingleStep(0.1)
        self.q5Value.setObjectName("q5Value")
        self.verticalLayout_11.addWidget(self.q5Value)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12)
        self.q6Value = QtWidgets.QDoubleSpinBox(self.tab)
        self.q6Value.setMaximum(1.0)
        self.q6Value.setSingleStep(0.1)
        self.q6Value.setObjectName("q6Value")
        self.verticalLayout_11.addWidget(self.q6Value)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelRes = QtWidgets.QLabel(self.tab)
        self.labelRes.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRes.setObjectName("labelRes")
        self.verticalLayout_2.addWidget(self.labelRes)
        self.resFirst = QtWidgets.QDoubleSpinBox(self.tab)
        self.resFirst.setDecimals(5)
        self.resFirst.setObjectName("resFirst")
        self.verticalLayout_2.addWidget(self.resFirst)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.buttonFirst = QtWidgets.QPushButton(self.tab)
        self.buttonFirst.setAutoDefault(False)
        self.buttonFirst.setObjectName("buttonFirst")
        self.verticalLayout_5.addWidget(self.buttonFirst)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.variantIdx = QtWidgets.QComboBox(self.tab_2)
        self.variantIdx.setObjectName("variantIdx")
        self.variantIdx.addItem("")
        self.variantIdx.addItem("")
        self.variantIdx.addItem("")
        self.variantIdx.addItem("")
        self.verticalLayout_8.addWidget(self.variantIdx)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.formulTab = QtWidgets.QLabel(self.tab_2)
        self.formulTab.setText("")
        self.formulTab.setAlignment(QtCore.Qt.AlignCenter)
        self.formulTab.setObjectName("formulTab")
        self.verticalLayout_7.addWidget(self.formulTab)
        self.label_m1 = QtWidgets.QLabel(self.tab_2)
        self.label_m1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_m1.setObjectName("label_m1")
        self.verticalLayout_7.addWidget(self.label_m1)
        self.m1Tab = QtWidgets.QSpinBox(self.tab_2)
        self.m1Tab.setMinimum(1)
        self.m1Tab.setMaximum(10000)
        self.m1Tab.setObjectName("m1Tab")
        self.verticalLayout_7.addWidget(self.m1Tab)
        self.label_m2 = QtWidgets.QLabel(self.tab_2)
        self.label_m2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_m2.setObjectName("label_m2")
        self.verticalLayout_7.addWidget(self.label_m2)
        self.m2Tab = QtWidgets.QSpinBox(self.tab_2)
        self.m2Tab.setProperty("value", 1)
        self.m2Tab.setObjectName("m2Tab")
        self.verticalLayout_7.addWidget(self.m2Tab)
        self.label_n = QtWidgets.QLabel(self.tab_2)
        self.label_n.setAlignment(QtCore.Qt.AlignCenter)
        self.label_n.setObjectName("label_n")
        self.verticalLayout_7.addWidget(self.label_n)
        self.nTab = QtWidgets.QSpinBox(self.tab_2)
        self.nTab.setMinimum(1)
        self.nTab.setMaximum(10000)
        self.nTab.setObjectName("nTab")
        self.verticalLayout_7.addWidget(self.nTab)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.resultTab = QtWidgets.QTextEdit(self.tab_2)
        self.resultTab.setObjectName("resultTab")
        self.verticalLayout_8.addWidget(self.resultTab)
        self.buttonTab = QtWidgets.QPushButton(self.tab_2)
        self.buttonTab.setAutoDefault(False)
        self.buttonTab.setObjectName("buttonTab")
        self.verticalLayout_8.addWidget(self.buttonTab)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.copyright = QtWidgets.QLabel(Dialog)
        self.copyright.setStyleSheet("")
        self.copyright.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.copyright.setObjectName("copyright")
        self.verticalLayout_3.addWidget(self.copyright)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Вычисление элементов комбинаторики"))
        self.label_14.setText(_translate("Dialog", "Выберете схему:"))
        self.chooseScheme.setItemText(0, _translate("Dialog", "Схема по условию"))
        self.chooseScheme.setItemText(1, _translate("Dialog", "Придуманная схема"))
        self.label_13.setText(_translate("Dialog", "Для заданной схемы составить формулу, выражающую событие В – схема работает безотказно в течение времени Т \n"
"через события Аi – i-ый элемент схемы работает безотказно в течение времени Т."))
        self.label_15.setText(_translate("Dialog", "Формула:"))
        self.q1Label.setText(_translate("Dialog", "Введите значение q1"))
        self.label_8.setText(_translate("Dialog", "Введите значение q2"))
        self.label_9.setText(_translate("Dialog", "Введите значение q3"))
        self.label_10.setText(_translate("Dialog", "Введите значение q4"))
        self.label_11.setText(_translate("Dialog", "Введите значение q5"))
        self.label_12.setText(_translate("Dialog", "Введите значение q6"))
        self.labelRes.setText(_translate("Dialog", "Результат:"))
        self.buttonFirst.setText(_translate("Dialog", "Получить результат"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Формулы комбинаторики"))
        self.label_2.setText(_translate("Dialog", "Формулировка задачи"))
        self.label.setText(_translate("Dialog", "Один студент выучил m1 из n вопросов программы, а второй m2. \n"
"Каждому из них задают по три вопроса. \n"
"Найти вероятность того, что не менее, чем на два вопроса правильно ответят:"))
        self.variantIdx.setItemText(0, _translate("Dialog", "оба студента"))
        self.variantIdx.setItemText(1, _translate("Dialog", "только первый студент"))
        self.variantIdx.setItemText(2, _translate("Dialog", "только один из них"))
        self.variantIdx.setItemText(3, _translate("Dialog", "хотя бы один из студентов"))
        self.label_6.setText(_translate("Dialog", "Формула для решения:"))
        self.label_m1.setText(_translate("Dialog", "Введите значение m1:"))
        self.label_m2.setText(_translate("Dialog", "Введите значение m2:"))
        self.label_n.setText(_translate("Dialog", "Введите значение n:"))
        self.label_7.setText(_translate("Dialog", "Результат:"))
        self.buttonTab.setText(_translate("Dialog", "Получить результат"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Расчет задачи"))
        self.copyright.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:9pt; font-style:italic;\">© Kirienko, Tokareva, Kolodin, 2018</span></p></body></html>"))

